// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOJCAHPfOgYgsibaTKE63qJ3sZMbs2AAQ',
    appId: '1:182025146080:web:dcc2d938b6a672a3c8ca85',
    messagingSenderId: '182025146080',
    projectId: 'vigor-workouch-411810',
    authDomain: 'vigor-workouch-411810.firebaseapp.com',
    storageBucket: 'vigor-workouch-411810.firebasestorage.app',
    measurementId: 'G-JTPNNB5LLE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWJC92kSKktW17FNTAKf2782b_JUHO0mQ',
    appId: '1:182025146080:android:60385d9e75d74179c8ca85',
    messagingSenderId: '182025146080',
    projectId: 'vigor-workouch-411810',
    storageBucket: 'vigor-workouch-411810.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtDHM_ZoLH5N6B0Te8nMbIfym9u4xil2A',
    appId: '1:182025146080:ios:45c90baa81d5a52ac8ca85',
    messagingSenderId: '182025146080',
    projectId: 'vigor-workouch-411810',
    storageBucket: 'vigor-workouch-411810.firebasestorage.app',
    androidClientId:
        '182025146080-62no00ami3a7hbgk6lc55gelek9nd0h5.apps.googleusercontent.com',
    iosClientId:
        '182025146080-t8pubo4cvdugvo39rd3ebanvd511k1qu.apps.googleusercontent.com',
    iosBundleId: 'com.vigor.workouch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtDHM_ZoLH5N6B0Te8nMbIfym9u4xil2A',
    appId: '1:182025146080:ios:45c90baa81d5a52ac8ca85',
    messagingSenderId: '182025146080',
    projectId: 'vigor-workouch-411810',
    storageBucket: 'vigor-workouch-411810.firebasestorage.app',
    androidClientId:
        '182025146080-62no00ami3a7hbgk6lc55gelek9nd0h5.apps.googleusercontent.com',
    iosClientId:
        '182025146080-t8pubo4cvdugvo39rd3ebanvd511k1qu.apps.googleusercontent.com',
    iosBundleId: 'com.vigor.workouch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOJCAHPfOgYgsibaTKE63qJ3sZMbs2AAQ',
    appId: '1:182025146080:web:b4e64a1d5803ed8cc8ca85',
    messagingSenderId: '182025146080',
    projectId: 'vigor-workouch-411810',
    authDomain: 'vigor-workouch-411810.firebaseapp.com',
    storageBucket: 'vigor-workouch-411810.firebasestorage.app',
    measurementId: 'G-RW45VEGR2P',
  );
}
